name: continuous deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main
    # paths:
    #   - 'web/**'
    #   - '!web/apps/mobile/**'

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{secrets.token}}

      - name: git identity
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
          cache-dependency-path: web/yarn.lock

      - name: install dependencies
        working-directory: web
        run: yarn --pure-lockfile

      - name: lerna release
        working-directory: web
        run: npx lerna publish --no-private
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}